reddit_clone_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reddit/', include("reddit_app.urls")),   
    path('user/', include("user_app.urls")),
]

user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    path("", views.login, name="login"), 
    path("signup/", views.signup, name="signup"), 
    path("login/", views.login, name="login"), 
    path("logout/", views.logout, name="logout"), 
    path("settings/", views.settings, name="settings"), 
    path("delete/", views.delete, name="delete"), 
    path("update-password/", views.update_password, name="update_password"), 
    path("request-reset-password/", views.request_reset_password, name="request_reset_password"), 
    path("reset-password/", views.reset_password, name="reset_password"), 
]

user_app/models.py
from django.db import models
from secrets import token_urlsafe

class PasswordReset(models.Model):
    email = models.CharField(max_length=100)
    token = models.CharField(max_length=40, default=token_urlsafe)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"Active: {self.active} // Token: {self.token}"

user_app/views.py
import django_rq
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from reddit_app.models import Post
from .models import PasswordReset
from . messaging import password_req_email;


def signup(request):
    context = {}

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('reddit_app:index'))

    if request.method == "POST":
        username = request.POST['user']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password: 
            if User.objects.create_user(username, email, password):
                return HttpResponseRedirect(reverse('user_app:login'))
            else:
                context = {
                    'error': 'Could not create user account - Please try again.'
                }
        else:
            context = {
                'error': 'Passwords did not match - Please try again.'
            }
    return render(request, 'user_app/signup.html', context)



def login(request):
    context = {}

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('reddit_app:index'))

    if request.method == "POST":
        user = authenticate(request, username=request.POST["username"], password= request.POST["password"])

        if user: 
            dj_login(request, user)
            return HttpResponseRedirect(reverse("reddit_app:index"))
        else: 
            context = {"error": "Invalid username or password combination"}
    
    return render(request, "user_app/login.html", context)

@login_required
def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('user_app:login'))


@login_required
def settings(request):
    context = {}
    user = request.user
    context={"user": user}

    return render(request, "user_app/settings.html", context)


@login_required
def delete(request):
    context = {}

    if request.method == "POST":
        password = request.POST['password']
        if request.user.check_password(password):
            if request.POST['confirm_deletion'] == "DELETE":
                if user:
                    print(f"deleting user {user}")
                    user.delete()
                    return HttpResponseRedirect(reverse('reddit_app:index'))
                else:
                    context = {"del_message": "Deletion failed"}
            else: 
                context = {"del_message": "you need to write DELETE"}
        else: 
            context = {"del_message": "wrong password"}

    return render(request, 'user_app/settings.html', context)

@login_required
def update_password(request):
    context = {}

    if request.method == "POST":
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        new_password_confirm = request.POST['new_password_confirm']

        if request.user.check_password(old_password):
            if new_password == new_password_confirm:
                user = get_object_or_404(User, username=request.user.username)
                user.set_password(new_password)
                user.save()
                context = {"pass_message": "Password changed"}

                return HttpResponseRedirect(reverse('user_app:login'))
            else:
                context = {"pass_message": "Passwords do not match"}
        else:
            context = {"pass_message": "Wrong password"}

    return render(request, 'user_app/settings.html', context)


def request_reset_password(request):
    context = {}
    if request.method == 'POST':
        email = request.POST['email']
        is_email_valid = User.objects.filter(email=email).exists()
    
        if is_email_valid:
            password_reset_request = PasswordReset()
            password_reset_request.email = email
            password_reset_request.save()

            django_rq.enqueue(password_req_email, {
                'reset_url': request.build_absolute_uri(reverse('user_app:reset_password')) + "?token=" + password_reset_request.token,
                'email': password_reset_request.email,
            })

            context = {"email_sent": True}

        else:
            context = {'message': 'This email does not exist in the database'}
    
    return render(request, 'user_app/request-reset-password.html', context)


def reset_password(request):
    context = {}
    token = request.GET.get('token', None)

    if request.method == 'POST':
        if token:
            email = request.POST['password-reset-email']
            password = request.POST['password-reset-password']
            password_confirm = request.POST['password-reset-password-confirm']

            if password == password_confirm: 
                is_token_valid = PasswordReset.objects.filter(token=token, active=True).exists()
                is_user_valid = User.objects.filter(email=email).exists()

                if is_token_valid and is_user_valid:
                    token = PasswordReset.objects.get(token=token)
                    token.active = False
                    token.save()

                    user = User.objects.get(email=email)
                    user.set_password(password)
                    user.save()

                    return redirect('user_app:login')

                else:
                    context = { 'message': 'token or email is invalid' }
            else:
                context = { 'message': 'passwords do not match' }
        else:
            context = {'message': 'no token provided'}

    return render(request, 'user_app/reset-password.html', context)

templates/user_app/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock title %}


{% block content %}
<h1>Log in</h1>
<hr>
<p>Do not have a user account? <a href="{% url 'user_app:signup' %}">Sign up here</a></p>

<form action="{% url "user_app:login" %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username">
    <input type="password" name="password" placeholder="password">
    <button>Login</button>
</form>

<p>Forgot your password? Reset it <a href="{% url 'user_app:request_reset_password' %}">here</a></p>


{% if error %}
    <p>{{ error }}</p>
{% endif %}
{% endblock content %}

templates/user_app/request-reset-password.html
{% extends "base.html" %}

{% block title %} Request reset password {% endblock title %}


{% block content %}
<h1>Request reset password</h1>
<form action="{% url "user_app:request_reset_password" %}" method="POST">
    {% csrf_token %}
    <input type="email" name="email" placeholder="email">
    <button>Request</button>
</form>
{% if email_sent %}
    <h3>An email with directions to reset your password has been sent to you!</h3>
{% endif %}

{% if message %}
    <p>{{ message }}</p>
{% endif %}

{% endblock content %}

templates/user_app/reset-password.html
{% extends "base.html" %}

{% block title %} Reset password {% endblock title %}


{% block content %}
<h1>Reset password</h1>
<form action="{{request.get_full_path}}" method="POST">
    {% csrf_token %}
    <input type="email" name="password-reset-email" placeholder="email">
    <input type="password" name="password-reset-password" placeholder="new password">
    <input type="password" name="password-reset-password-confirm" placeholder="confirm new password">
    <button>Change password</button>
</form>


{% if message %}
    <p>{{ message }}</p>
{% endif %}

{% endblock content %}

templates/user_app/settings.html
{% extends "base.html" %}

{% block title %} Settings {% endblock title %}

{% block content %}
<h1>Settings</h1>

<h3 class="settings">Update password</h3>
<div class="post-form-container update-password">
    <form class="post-form" method="POST" action="{% url 'user_app:update_password' %}">
        {% csrf_token %}
        <input type="password" name="old_password" placeholder="Old Password">
        <input type="password" name="new_password" placeholder="New Password">
        <input type="password" name="new_password_confirm" placeholder="Confirm New Password">
        <button>Update password</button>
    </form>
    {% if pass_message %}
        <p>{{pass_message}}</p>
    {% endif %}
</div>

<h3 class="settings">Delete user</h3>
<div class="post-form-container delete-user">
    <form class="post-form" method="POST" action="{% url "user_app:delete" %}">
        {% csrf_token %}
        <input type="password" name="password" placeholder="confirm password">
        <input type="text" name="confirm_deletion" placeholder="type DELETE">
        <button>Delete user</button>
    </form>
    {% if del_message %}
        <p>{{del_message}}</p>
    {% endif %}
</div>

{% if error %}
    <p>{{ error }}</p>
{% endif %}
{% endblock content %}

templates/user_app/signup.html
{% extends "base.html" %}

{% block title %} Sign up {% endblock title %}

{% block content %}
<h1>Sign up</h1>

<form action="{% url 'user_app:signup' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="user" placeholder="username">
    <input type="email" name="email" placeholder="email">
    <input type="password" name="password" placeholder="password">
    <input type="password" name="confirm_password" placeholder="confirm password">
    <button>Sign up</button>
</form>

{% if error %}
    <p>{{ error }}</p>
{% endif %}
{% endblock content %}