reddit_app/urls.py
from django.urls import path
from . import views
from .api import PostView, VoteView, PostDetail

app_name = 'reddit_app'

urlpatterns = [
    path("", views.index, name="index"), 
    path("trending/", views.trending, name="trending"), 
    path("profile/", views.profile, name="profile"), 
    path("notifications/", views.notifications, name="notifications"), 
    path("post/<int:post_id>", views.single_post, name="single_post"), 
    path("post/<int:post_id>/comment", views.comment, name="comment"), 
    path("post/<int:post_id>/delete", views.delete_post, name="delete_post"), 
    path('posts/', PostView.as_view()),
    path('posts/<int:pk>', PostDetail.as_view()),
    path('votes/', VoteView.as_view()),
]

reddit_clone_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reddit/', include("reddit_app.urls")),   
    path('user/', include("user_app.urls")),
]

user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    path("", views.login, name="login"), 
    path("signup/", views.signup, name="signup"), 
    path("login/", views.login, name="login"), 
    path("logout/", views.logout, name="logout"), 
    path("settings/", views.settings, name="settings"), 
    path("delete/", views.delete, name="delete"), 
    path("update-password/", views.update_password, name="update_password"), 
    path("request-reset-password/", views.request_reset_password, name="request_reset_password"), 
    path("reset-password/", views.reset_password, name="reset_password"), 
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %} <!--- title inserted from other template  --> {% endblock title %} </title>
         {% load static %} <link rel="stylesheet" href="{% static "global/css/styles.css" %}" />
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li>
                        <h3>Djeddit</h3>
                    </li>
                    <li>
                        <a href="{% url 'reddit_app:index' %}">Home</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'reddit_app:profile' %}">Profile</a>
                        </li>
                        <li>
                            <a href="{% url 'user_app:settings' %}">Settings</a>
                        </li>
                        <li>
                            <a href="{% url 'reddit_app:notifications' %}">Notifications</a>
                        </li>
                        <li>
                            <a href="{% url 'user_app:logout' %}">Log out</a>
                        </li>
                    {% else %}
                    <li>
                        <a href="{% url 'user_app:login' %}">Log in</a>
                    </li>
                    <li>
                        <a href="{% url 'user_app:signup' %}">Sign up</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <a href="{% url 'reddit_app:notifications' %}">
                <div class="notification-popup">     
                    <h3>Notification</h3>
                    <p>Hello</p>
                </div>
            </a>
            {% block content %}
            <!-- Main content inserted here -->
            {% endblock content %}
        </main>
    </body>
</html>