reddit_app/urls.py
from django.urls import path
from . import views
from .api import PostView, VoteView, PostDetail

app_name = 'reddit_app'

urlpatterns = [
    path("", views.index, name="index"), 
    path("trending/", views.trending, name="trending"), 
    path("profile/", views.profile, name="profile"), 
    path("notifications/", views.notifications, name="notifications"), 
    path("post/<int:post_id>", views.single_post, name="single_post"), 
    path("post/<int:post_id>/comment", views.comment, name="comment"), 
    path("post/<int:post_id>/delete", views.delete_post, name="delete_post"), 
    path('posts/', PostView.as_view()),
    path('posts/<int:pk>', PostDetail.as_view()),
    path('votes/', VoteView.as_view()),
]

reddit_clone_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reddit/', include("reddit_app.urls")),   
    path('user/', include("user_app.urls")),
]

user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    path("", views.login, name="login"), 
    path("signup/", views.signup, name="signup"), 
    path("login/", views.login, name="login"), 
    path("logout/", views.logout, name="logout"), 
    path("settings/", views.settings, name="settings"), 
    path("delete/", views.delete, name="delete"), 
    path("update-password/", views.update_password, name="update_password"), 
    path("request-reset-password/", views.request_reset_password, name="request_reset_password"), 
    path("reset-password/", views.reset_password, name="reset_password"), 
]

reddit_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    votes = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Author: {self.author} // Title: {self.title}"


    def date_posted(self):
        return self.created_at.strftime('%B %d %Y')


class Comment(models.Model):
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"User: {self.author} // Commented: {self.text} // On post: {self.post}"
    
    def date_commented(self):
        return self.created_at.strftime('%B %d %Y')


class Vote(models.Model):
    vote = models.BooleanField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.vote} - {self.user} - {self.post}"
        

class Notification(models.Model):
    reciever = models.ForeignKey(User, related_name='notifications', on_delete=models.CASCADE)
    sender = models.ForeignKey(User, related_name='sent_notifications', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Sender: {self.sender} // Reciever: {self.reciever} // On post: {self.post}"

    def date_sent(self):
        return self.created_at.strftime('%B %d %Y')

    

reddit_app/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required
from . models import Post, Comment, Vote, Notification

def index(request):
    posts = Post.objects.all().order_by('-created_at')
    context = {"posts": posts}
    
    return render(request, "reddit_app/index.html", context)


def trending(request):
    posts = Post.objects.all().order_by('-votes')
    context = {"posts": posts}

    return render(request, "reddit_app/trending.html", context)


def single_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comment = Comment()
    comments = Comment.objects.filter(post=post)
    context = {"post": post, "comments": comments}
    return render(request, "reddit_app/single_post.html", context)


def profile(request):
    user = request.user
    posts = Post.objects.filter(author=user)
    context = {"posts": posts, "user": user}

    return render(request, "reddit_app/profile.html", context)


@login_required
def comment(request, post_id):
    if request.method == "POST":
        text = request.POST["text"]
        author = request.user
        Comment.objects.create(text=text, author=author, post_id=post_id)
        
        return redirect("reddit_app:single_post", post_id=post_id)


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    
    return HttpResponseRedirect(reverse('reddit_app:profile'))


def notifications(request):
    user = request.user
    notifications = Notification.objects.filter(reciever=user, read=False)
    read_notifications = Notification.objects.filter(reciever=user, read=True)

    if request.method == "POST":
        notifications.update(read=True)
 
    context = {"notifications": notifications, "read_notifications": read_notifications}
    
    return render(request, "reddit_app/notifications.html", context)

templates/reddit_app/index.html
{% extends "base.html" %}

{% block title %} Home {% endblock title %}

{% block content %}
{% if user.username %}
    <h1>Welcome, {{user.username}}.</h1>
{% endif %}

{% if request.user.is_authenticated %}
<div>
    <h2>Create a new post</h2>
    <div class="post-form-container">
        <form class="post-form" method="POST">
            {% csrf_token %}
            <input type="text" name="title" placeholder="title">
            <textarea name="text" placeholder="write your post"></textarea>
            <input type="hidden" name="user_id" value="{{ user.id }}">
            <input type="hidden" name="username" value="{{ user.username }}">  
            <button id="create-post">Create post</button>
        </form>
    </div>
    {% if error %} <p>{{error}}</p> {% endif %}
</div>
{% endif %}

<div class="post-nav">
    <a href="{% url 'reddit_app:index' %}">
        <h2>New posts</h2>
    </a>
    <a href="{% url 'reddit_app:trending' %}">
        <h2>Trending posts</h2>
    </a>
</div>

<div id="posts">
    {% if posts.count %}
        {% for post in posts %}
            <div class="post-container post-{{post.id}}" style="border: 1px solid black; margin-bottom: 10px;">
                <div>
                    <p class="upvote post-vote" data-votes="{{post.votes}}" data-postid="{{ post.id }}" data-userid="{{ user.id }}">&uarr;</p>
                    <p class="votes">{{post.votes}}</p>
                    <p class="downvote post-vote" data-votes="{{post.votes}}" data-postid="{{ post.id }}" data-userid="{{ user.id }}">&darr;</p>
                </div>
                <div class="post">
                    <a href={% url 'reddit_app:single_post' post.id %}>
                        <h3>{{post.title}}</h3>
                        <div class="post-info">
                            <span>Posted by: {{post.author}}</span>
                            <p>{{post.date_posted}}</p>
                        </div>
                        <p>{{post.text}}</p>
                    </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>There are no posts</p>
    {% endif %}
</div>

{% load static %}
<script src="{% static "global/js/notification.js" %}"></script>
<script src="{% static "global/js/cookie.js" %}"></script>
<script src="{% static "global/js/index.js" %}"></script>
{% endblock content %}

templates/reddit_app/notifications.html
{% extends "base.html" %}

{% block title %} Notifications {% endblock title %}

{% block content %}
    <h1>Notifications</h1>
    <form method="POST" action="{% url 'reddit_app:notifications' %}">
        {% csrf_token %}
        <button>Mark all as read</button>
    </form>
    {% if notifications.count %}
        <div class="notifications">
        <h2>Unread notifications</h2>
            {% for notification in notifications %}
                    <div class="notification">
                        <a href="{% url 'reddit_app:single_post' notification.post_id %}">
                            <span>{{notification.date_sent}}</span>
                            <p>{{notification.sender}} has left a comment on your post "{{notification.post.title}}"</p>
                        </a>
                    </div>
            {% endfor %}
        </div>
    {% else %}
        <h2>Unread notifications</h2>
        <p>No new notifications</p>
    {% endif %}
    {% if read_notifications.count %}
        <div class="notifications">
        <h2>Read notifications</h2>
            {% for read_notification in read_notifications %}
                    <div class="notification">
                        <a href="{% url 'reddit_app:single_post' read_notification.post_id %}">
                            <span>{{read_notification.date_sent}}</span>
                            <p>{{read_notification.sender}} has left a comment on your post "{{read_notification.post.title}}"</p>
                        </a>
                    </div>
            {% endfor %}
        </div>
    {% endif %}

{% load static %}
<script src="{% static "global/js/notification.js" %}"></script>
{% endblock content %}

templates/reddit_app/profile.html
{% extends "base.html" %}

{% block title %} Profile {% endblock title %}

{% block content %}
<h1>Profile</h1>
<div>
    <h2>Welcome, {{user.username}}.</h2>
    <p>This is a history of your posts.</p>
    <h3>Posts</h3>
    <div class="profile-posts">
        {% if posts.count %}
            {% for post in posts %}
                <div class="profile-post profile-post-{{post.id}}">
                    <a href={% url 'reddit_app:single_post' post.id %}>
                        <h3>{{post.title}}</h3>
                        <span>{{post.date_posted}}</span>
                        <span>Score: {{post.votes}}</span>
                        <p>{{post.text}}</p>
                        <a href="{% url "reddit_app:delete_post" post.id %}"><button>Delete post</button></a>
                        <button data-postid={{post.id}} class="show-update btn-{{post.id}}">Update post</button>
                    </a>
                    <div class="update-post-form post-{{post.id}}">
                        <form> 
                            <input type="text" name="title" value="{{post.title}}">
                            <textarea name="text">{{post.text}}</textarea>
                            <button data-postid={{post.id}} type="button" class="update-post">Update post</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>You do not have any posts yet.</p>
        {% endif %}
    </div>

{% if error_message %} <p>{{error_message}}</p> {% endif %}

{% load static %}
<script src="{% static 'global/js/notification.js' %}"></script>
<script src="{% static 'global/js/cookie.js' %}"></script>
<script src="{% static "global/js/profile.js" %}"></script>
{% endblock content %}

templates/reddit_app/single_post.html
{% extends 'base.html' %} {% block title %} {{post.title}} {% endblock title %}

{% block content %}

<div class="post-container single-post post-{{post.id}}">
    <div>
        <p class="upvote post-vote" data-votes="{{post.votes}}" data-postid="{{ post.id }}" data-userid="{{ user.id }}">&uarr;</p>
        <p class="votes">{{post.votes}}</p>
        <p class="downvote post-vote" data-votes="{{post.votes}}" data-postid="{{ post.id }}" data-userid="{{ user.id }}">&darr;</p>
    </div>
    <div>
        <h1>{{post.title}}</h1>
        <div class="post-info">
            <span>Posted by: {{post.author}}</span>
            <p>{{post.date_posted}}</p>
        </div>
        <p>{{post.text}}</p>
    </div>
</div>

<div id="comments">
    <h2>Comments ({{comments.count}})</h2>
    {% if comments.count %}
        {% for comment in comments %}
            <div class="comment">
                <span>{{comment.author}} - {{comment.date_commented}}</span>
                <p>{{comment.text}}</p>
            </div>
        {% endfor %}
    {% else %}
        <p>Be the first to comment!</p>
    {% endif %}
</div>
{% if request.user.is_authenticated %}
    <div id="comment-form">
        <form method="POST" action="{% url "reddit_app:comment" post.id %}">
            {% csrf_token %}
            <textarea name="text" placeholder="write your comment"></textarea>
            <button>Comment</button>
        </form>
    </div>
{% else %}
    <p>Log in <a href="{% url "user_app:login" %}">here</a> to comment</p>
{% endif %}

{% load static %}
<script src="{% static 'global/js/notification.js' %}"></script>
<script src="{% static "global/js/cookie.js" %}"></script>
<script src="{% static "global/js/index.js" %}"></script>
{% endblock content %}

templates/reddit_app/trending.html
{% extends "base.html" %}

{% block title %} Home {% endblock title %}

{% block content %}
{% if user.username %}
    <h1>Welcome, {{user.username}}.</h1>
{% endif %}

{% if request.user.is_authenticated %}
<div>
    <h2>Create a new post</h2>
    <div class="post-form-container">
        <form class="post-form" method="POST">
            {% csrf_token %}
            <input type="text" name="title" placeholder="title">
            <textarea name="text" placeholder="write your post"></textarea>
            <input type="hidden" name="user_id" value="{{ user.id }}"> 
            <button id="create-post">Create post</button>
        </form>
    </div>
    {% if error %} <p>{{error}}</p> {% endif %}
</div>
{% endif %}

<div class="post-nav">
    <a href="{% url 'reddit_app:index' %}">
        <h2>New posts</h2>
    </a>
    <a href="{% url 'reddit_app:trending' %}">
        <h2>Trending posts</h2>
    </a>
</div>
<div id="posts">
    {% if posts.count %}
        {% for post in posts %}
            <div class="post-container post-{{post.id}}" style="border: 1px solid black; margin-bottom: 10px;">
                <div>
                    <p class="upvote post-vote" data-votes="{{post.votes}}" data-postid="{{ post.id }}" data-userid="{{ user.id }}">&uarr;</p>
                    <p class="votes">{{post.votes}}</p>
                    <p class="downvote post-vote" data-votes="{{post.votes}}" data-postid="{{ post.id }}" data-userid="{{ user.id }}">&darr;</p>
                </div>
                <div class="post">
                    <a href={% url 'reddit_app:single_post' post.id %}>
                        <h3>{{post.title}}</h3>
                        <div class="post-info">
                            <span>Posted by: {{post.author}}</span>
                            <p>{{post.date_posted}}</p>
                        </div>
                        <p>{{post.text}}</p>
                    </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>There are no posts</p>
    {% endif %}

</div>

{% load static %}
<script src="{% static 'global/js/notification.js' %}"></script>
<script src="{% static "global/js/cookie.js" %}"></script>
<script src="{% static "global/js/index.js" %}"></script>
{% endblock content %}